# ray_status.yml
---
- name: Ray status on controller
  hosts: controller
  become: true
  vars:
    container_name: ray-head
  tasks:
    - name: Run ray status inside head container
      ansible.builtin.command: docker exec {{ container_name }} ray status
      register: ray_status
      changed_when: false

    - name: Print ray status
      ansible.builtin.debug:
        var: ray_status.stdout

- name: Ray worker process check
  hosts: spark
  become: true
  vars:
    worker_container_name: ray-worker
  tasks:
    - name: Show ray processes inside worker container
      ansible.builtin.shell: |
        set -o pipefail
        docker exec {{ worker_container_name }} sh -lc \
          "ps aux | egrep 'ray::|raylet|gcs|dashboard|ray start' || true"
      args:
        executable: /bin/bash
      register: worker_ray_ps
      changed_when: false

    - name: Print worker process summary
      ansible.builtin.debug:
        msg: |
          {{ inventory_hostname }}:
          {{ worker_ray_ps.stdout | default('no output') }}