# ray_vllm_cluster.yml
---
# Inventory layout assumed:
#   [controller]
#   blossom
#
#   [spark]
#   bubbles
#   bunny
#   buttercup
#
# Controller runs the Ray head. spark group runs Ray workers.

- name: Start Ray head container on controller
  hosts: controller
  become: true
  vars:
    vllm_image: "nvcr.io/nvidia/vllm:25.11-py3"
    mn_if_name: "enp1s0f0np0"
    hf_home: "/mnt/hfcache"
    ray_port: 6379
    container_name: "ray-head"
    shm_size: "10.24g"
  tasks:
    - name: Ensure Python + Docker SDK are present for Ansible docker_container
      ansible.builtin.apt:
        name:
          - python3-pip
        update_cache: true

    - name: Install Docker SDK for Python
      ansible.builtin.pip:
        name: docker

    - name: Read controller IP on {{ mn_if_name }}
      ansible.builtin.set_fact:
        vllm_host_ip: "{{ hostvars[inventory_hostname]['ansible_' + mn_if_name].ipv4.address }}"

    - name: Start Ray head container (host network, privileged, GPUs)
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ vllm_image }}"
        state: started
        restart_policy: unless-stopped
        network_mode: host
        privileged: true
        shm_size: "{{ shm_size }}"
        volumes:
          - "{{ hf_home }}:/root/.cache/huggingface"
        env:
          VLLM_HOST_IP: "{{ vllm_host_ip }}"
          UCX_NET_DEVICES: "{{ mn_if_name }}"
          NCCL_SOCKET_IFNAME: "{{ mn_if_name }}"
          OMPI_MCA_btl_tcp_if_include: "{{ mn_if_name }}"
          GLOO_SOCKET_IFNAME: "{{ mn_if_name }}"
          TP_SOCKET_IFNAME: "{{ mn_if_name }}"
          RAY_memory_monitor_refresh_ms: "0"
          MASTER_ADDR: "{{ vllm_host_ip }}"
          RAY_NODE_IP_ADDRESS: "{{ vllm_host_ip }}"
          RAY_OVERRIDE_NODE_IP_ADDRESS: "{{ vllm_host_ip }}"
        device_requests:
          - driver: nvidia
            count: -1
            capabilities: [["gpu"]]
        entrypoint: /bin/bash
        command: >-
          -lc "ray start --block --head --port={{ ray_port }} --node-ip-address={{ vllm_host_ip }}"

- name: Start Ray worker containers on spark group
  hosts: spark
  become: true
  vars:
    # If you want workers to use the same image as head, set it here or in group_vars/spark.yml
    vllm_image: "ericlewisplease/vllm:latest"
    mn_if_name: "enp1s0f0np0"
    hf_home: "/mnt/hfcache"
    ray_port: 6379
    shm_size: "10.24g"
    # Use controller as head source of truth
    head_host: "{{ groups['controller'][0] }}"
    head_ip: "{{ hostvars[head_host].vllm_host_ip | default(hostvars[head_host]['ansible_' + hostvars[head_host].mn_if_name].ipv4.address) }}"
  tasks:
    - name: Ensure Python + Docker SDK are present for Ansible docker_container
      ansible.builtin.apt:
        name:
          - python3-pip
        update_cache: true

    - name: Install Docker SDK for Python
      ansible.builtin.pip:
        name: docker

    - name: Read worker IP on {{ mn_if_name }}
      ansible.builtin.set_fact:
        vllm_host_ip: "{{ hostvars[inventory_hostname]['ansible_' + mn_if_name].ipv4.address }}"

    - name: Start Ray worker container (host network, privileged, GPUs)
      community.docker.docker_container:
        name: "ray-worker"
        image: "{{ vllm_image }}"
        state: started
        restart_policy: unless-stopped
        network_mode: host
        privileged: true
        shm_size: "{{ shm_size }}"
        volumes:
          - "{{ hf_home }}:/root/.cache/huggingface"
        env:
          VLLM_HOST_IP: "{{ vllm_host_ip }}"
          UCX_NET_DEVICES: "{{ mn_if_name }}"
          NCCL_SOCKET_IFNAME: "{{ mn_if_name }}"
          OMPI_MCA_btl_tcp_if_include: "{{ mn_if_name }}"
          GLOO_SOCKET_IFNAME: "{{ mn_if_name }}"
          TP_SOCKET_IFNAME: "{{ mn_if_name }}"
          RAY_memory_monitor_refresh_ms: "0"
          MASTER_ADDR: "{{ head_ip }}"
          RAY_NODE_IP_ADDRESS: "{{ vllm_host_ip }}"
          RAY_OVERRIDE_NODE_IP_ADDRESS: "{{ vllm_host_ip }}"
        device_requests:
          - driver: nvidia
            count: -1
            capabilities: [["gpu"]]
        entrypoint: /bin/bash
        command: >-
          -lc "ray start --block --address={{ head_ip }}:{{ ray_port }} --node-ip-address={{ vllm_host_ip }}"
