# ray_vllm_cluster.yml
---
- name: Start Ray head container on controller
  hosts: controller
  become: true
  gather_facts: true
  collections:
    - community.docker
  vars:
    vllm_image: "nvcr.io/nvidia/vllm:25.11-py3"
    mn_if_name: "enp1s0f0np0"
    hf_home: "/mnt/hfcache"
    ray_port: 6379
    container_name: "ray-head"
    shm_size: "10.24g"

    # Default: do NOT install deps during run (Semaphore-friendly)
    install_deps: false

  pre_tasks:
    - name: Preflight - must be root via become
      ansible.builtin.command: id -u
      register: uid_root
      changed_when: false

    - name: Fail if become is not active
      ansible.builtin.fail:
        msg: "Become is not active (uid={{ uid_root.stdout }}). Fix Semaphore sudo/become settings."
      when: uid_root.stdout != "0"

    - name: (Optional) Install deps (one-time)
      when: install_deps
      block:
        - name: apt deps
          ansible.builtin.apt:
            name: [python3-pip, python3-docker]
            update_cache: true
        - name: pip docker (fallback)
          ansible.builtin.pip:
            name: docker

  tasks:
    - name: Compute controller IP (prefer {{ mn_if_name }}, fallback to default/ansible_host)
      ansible.builtin.set_fact:
        vllm_host_ip: >-
          {{
            (hostvars[inventory_hostname]['ansible_' + mn_if_name].ipv4.address
             if ('ansible_' + mn_if_name) in hostvars[inventory_hostname]
             else (ansible_facts.get('ansible_default_ipv4', {}).get('address')
                   or ansible_host
                   or inventory_hostname))
          }}
        vllm_ip_source: >-
          {{
            ('interface:' + mn_if_name)
            if ('ansible_' + mn_if_name) in hostvars[inventory_hostname]
            else 'fallback:' + (ansible_facts.get('ansible_default_ipv4', {}).get('address')
                                or ansible_host
                                or inventory_hostname)
          }}

    - name: Fail if controller IP could not be determined
      ansible.builtin.fail:
        msg: "Unable to determine controller IP (mn_if_name={{ mn_if_name }}, ansible_default_ipv4={{ ansible_facts.get('ansible_default_ipv4', {}) }}, ansible_host={{ ansible_host | default('') }})"
      when: vllm_host_ip is undefined or vllm_host_ip | length == 0

    - name: Start Ray head container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ vllm_image }}"
        state: started
        restart_policy: unless-stopped
        network_mode: host
        privileged: true
        shm_size: "{{ shm_size }}"
        volumes:
          - "{{ hf_home }}:/root/.cache/huggingface"
        env:
          VLLM_HOST_IP: "{{ vllm_host_ip }}"
          UCX_NET_DEVICES: "{{ mn_if_name }}"
          NCCL_SOCKET_IFNAME: "{{ mn_if_name }}"
          OMPI_MCA_btl_tcp_if_include: "{{ mn_if_name }}"
          GLOO_SOCKET_IFNAME: "{{ mn_if_name }}"
          TP_SOCKET_IFNAME: "{{ mn_if_name }}"
          RAY_memory_monitor_refresh_ms: "0"
          MASTER_ADDR: "{{ vllm_host_ip }}"
          RAY_NODE_IP_ADDRESS: "{{ vllm_host_ip }}"
          RAY_OVERRIDE_NODE_IP_ADDRESS: "{{ vllm_host_ip }}"
        device_requests:
          - driver: nvidia
            count: -1
            capabilities: [["gpu"]]
        entrypoint: /bin/bash
        command: >-
          -lc "ray start --block --head --port={{ ray_port }} --node-ip-address={{ vllm_host_ip }}"

- name: Start Ray worker containers on spark group
  hosts: spark
  become: true
  gather_facts: true
  collections:
    - community.docker
  vars:
    vllm_image: "nvcr.io/nvidia/vllm:25.11-py3"
    mn_if_name: "enp1s0f0np0"
    hf_home: "/mnt/hfcache"
    ray_port: 6379
    shm_size: "10.24g"
    install_deps: false
    head_host: "{{ groups['controller'][0] }}"
    head_ip: "{{ hostvars[head_host].ansible_host | default(head_host) }}"

  pre_tasks:
    - name: Preflight - must be root via become
      ansible.builtin.command: id -u
      register: uid_root
      changed_when: false

    - name: Fail if become is not active
      ansible.builtin.fail:
        msg: "Become is not active (uid={{ uid_root.stdout }}). Fix Semaphore sudo/become settings."
      when: uid_root.stdout != "0"

    - name: (Optional) Install deps (one-time)
      when: install_deps
      block:
        - name: apt deps
          ansible.builtin.apt:
            name: [python3-pip, python3-docker]
            update_cache: true
        - name: pip docker (fallback)
          ansible.builtin.pip:
            name: docker

  tasks:
    - name: Compute worker IP (prefer {{ mn_if_name }}, fallback to default/ansible_host)
      ansible.builtin.set_fact:
        vllm_host_ip: >-
          {{
            (hostvars[inventory_hostname]['ansible_' + mn_if_name].ipv4.address
             if ('ansible_' + mn_if_name) in hostvars[inventory_hostname]
             else (ansible_facts.get('ansible_default_ipv4', {}).get('address')
                   or ansible_host
                   or inventory_hostname))
          }}
        vllm_ip_source: >-
          {{
            ('interface:' + mn_if_name)
            if ('ansible_' + mn_if_name) in hostvars[inventory_hostname]
            else 'fallback:' + (ansible_facts.get('ansible_default_ipv4', {}).get('address')
                                or ansible_host
                                or inventory_hostname)
          }}

    - name: Fail if worker IP could not be determined
      ansible.builtin.fail:
        msg: "Unable to determine worker IP (mn_if_name={{ mn_if_name }}, ansible_default_ipv4={{ ansible_facts.get('ansible_default_ipv4', {}) }}, ansible_host={{ ansible_host | default('') }})"
      when: vllm_host_ip is undefined or vllm_host_ip | length == 0

    - name: Start Ray worker container
      community.docker.docker_container:
        name: "ray-worker"
        image: "{{ vllm_image }}"
        state: started
        restart_policy: unless-stopped
        network_mode: host
        privileged: true
        shm_size: "{{ shm_size }}"
        volumes:
          - "{{ hf_home }}:/root/.cache/huggingface"
        env:
          VLLM_HOST_IP: "{{ vllm_host_ip }}"
          UCX_NET_DEVICES: "{{ mn_if_name }}"
          NCCL_SOCKET_IFNAME: "{{ mn_if_name }}"
          OMPI_MCA_btl_tcp_if_include: "{{ mn_if_name }}"
          GLOO_SOCKET_IFNAME: "{{ mn_if_name }}"
          TP_SOCKET_IFNAME: "{{ mn_if_name }}"
          RAY_memory_monitor_refresh_ms: "0"
          MASTER_ADDR: "{{ head_ip }}"
          RAY_NODE_IP_ADDRESS: "{{ vllm_host_ip }}"
          RAY_OVERRIDE_NODE_IP_ADDRESS: "{{ vllm_host_ip }}"
        device_requests:
          - driver: nvidia
            count: -1
            capabilities: [["gpu"]]
        entrypoint: /bin/bash
        command: >-
          -lc "ray start --block --address={{ head_ip }}:{{ ray_port }} --node-ip-address={{ vllm_host_ip }}"
